exports.NEW_DOCUMENT = "NEW_DOCUMENT";
exports.WRITE_NEW_FILE_NEEDED = "WRITE_NEW_FILE_NEEDED";
exports.NEW_FILE_WRITTEN = "NEW_FILE_WRITTEN";
exports.SAVE_NEEDED = "SAVE_NEEDED";
exports.SAVED = "SAVED";
exports.SAVEFILE = "SAVEFILE";
exports.OPENFILE = "OPENFILE";